module.exports = {
  id: 'BN654123',
  extId: 'BN6522',
  updated: '2019/10/16',
  updatedBy: 'The chief',
  name: 'Upd. Boden New British',
  feed: 'Upd. Commision Factory',
  commissionType: 'euros',
  commissionRates:
    { base: '12.00',
      min: '11.00',
      max: '13.00',
    },
  classifications: ['Clothing', 'Other'],
  summary: 'Some updated summary',
  website: 'www.boden.com.au/updated',
  trackingUrl: 'www.boden.com.au/upd%&',
  terms: 'Some updated terms',
  status: 'active',
  image: 'https://picsum.photos/id/367/500/500',
}
