module.exports = {
  id: 'BN654123',
  extId: 'BN6522',
  updated: '2018-10-15T12:40:31.965Z',
  updatedBy: 'Julian Gregov',
  name: 'Boden New British',
  feed: 'Commision Factory',
  commissionType: 'dollars',
  commissionRates:
    { base: 5,
      min: 2,
      max: 7,
    },
  classifications: ['clothing'],
  summary: 'Some real summary',
  website: 'www.boden.com.au',
  trackingUrl: 'www.boden.com.au/offers_today%&',
  terms: 'Some terms',
  status: 'active',
}
