module.exports = {
  id: 'BN654123',
  extId: 'BN6522',
  updated: '2018/10/15',
  updatedBy: 'Julian Gregov',
  name: 'Boden New British',
  feed: 'Commision Factory',
  commissionType: 'dollars',
  commissionRates:
    { base: '5.00',
      min: '2.00',
      max: '7.00',
    },
  classifications: ['Clothing'],
  summary: 'Some real summary',
  website: 'www.boden.com.au',
  trackingUrl: 'www.boden.com.au/offers_today%&',
  terms: 'Some terms',
  status: 'active',
  image: '',
}
